import type { Metadata } from "next";
import NavigationBar from "@/components/site/NavigationBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className="flex h-dvh flex-col overflow-hidden antialiased">
        <NavigationBar></NavigationBar>
        <main className="min-h-0 flex-1">{children}</main>
      </body>
    </html>
  );
}
