import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Rubik } from "next/font/google";
import NavigationBar from "@/components/site/NavigationBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const interMain = Inter({
  variable: "--font-inter-mono",
  subsets: ["latin"],
  fallback:["--font-geist-sans"]
});

const testtest = Rubik({
  variable: '--font-rubik-norm',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${interMain.className} antialiased overflow-hidden `}
      >
        <NavigationBar></NavigationBar>
        <main>{children}</main>
      </body>
    </html>
  );
}
